config/routes.rb
Rails.application.routes.draw do
  resources :mailboxes
  get 'pages/index'
  root to: 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mailbox.rb
class Mailbox < ApplicationRecord
  serialize :data, MailboxData
end

app/models/mailbox_data.rb
class MailboxData
  include Virtus.model
  attribute :uid, String
  attribute :iname, String
  attribute :sex, String
  attribute :ready, String
  attribute :hintq, String
  attribute :aliases, String
  attribute :enabled, String
  attribute :maillist, String
  attribute :fname, String
  attribute :birth_date, String
  attribute :login, String
  attribute :fio, String
  
  def self.dump(preferences)
    preferences.to_hash
  end

  def self.load(preferences)
    new(preferences)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mailboxes_controller.rb
class MailboxesController < ApplicationController
  before_action :set_mailbox, only: [:show, :edit, :update, :destroy]

  # GET /mailboxes
  def index
    @mailboxes = Mailbox.all
  end

  # GET /mailboxes/1
  def show
  end

  # GET /mailboxes/new
  def new
    @mailbox = Mailbox.new
  end

  # GET /mailboxes/1/edit
  def edit
  end

  # POST /mailboxes
  def create
    @mailbox = Mailbox.new(mailbox_params)

    if @mailbox.save
      redirect_to @mailbox, notice: 'Mailbox was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /mailboxes/1
  def update
    if @mailbox.update(mailbox_params)
      redirect_to @mailbox, notice: 'Mailbox was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /mailboxes/1
  def destroy
    @mailbox.destroy
    redirect_to mailboxes_url, notice: 'Mailbox was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mailbox
      @mailbox = Mailbox.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def mailbox_params
      params.require(:mailbox).permit(:name, data: [:iname, :sex, :aliases, :fname, :birth_date, :fio])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mailboxes_helper.rb
module MailboxesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YandexPdd</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/mailboxes/_form.html.erb
<%= simple_form_for(@mailbox) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.simple_fields_for :data do |data| %>
    <%= data.input :iname %>
    <%= data.input :sex %>
<% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/mailboxes/edit.html.erb
<h1>Editing Mailbox</h1>

<%= render 'form', mailbox: @mailbox %>

<%= link_to 'Show', @mailbox %> |
<%= link_to 'Back', mailboxes_path %>

app/views/mailboxes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mailboxes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mailboxes.each do |mailbox| %>
      <tr>
        <td><%= mailbox.name %></td>
        <td><%= mailbox.data.to_hash %></td>
        <td><%= link_to 'Show', mailbox %></td>
        <td><%= link_to 'Edit', edit_mailbox_path(mailbox) %></td>
        <td><%= link_to 'Destroy', mailbox, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mailbox', new_mailbox_path %>

app/views/mailboxes/new.html.erb
<h1>New Mailbox</h1>

<%= render 'form', mailbox: @mailbox %>

<%= link_to 'Back', mailboxes_path %>

app/views/mailboxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mailbox.name %>
</p>

<p>
  <strong>Data:</strong>
  <%= @mailbox.data.to_hash %>
</p>

<%= link_to 'Edit', edit_mailbox_path(@mailbox) %> |
<%= link_to 'Back', mailboxes_path %>

app/views/pages/index.html.erb
<div class="container center">
  <h1>yandex#pdd</h1>
</div>